/* Phase history (CPHD) container and image formation by backprojection.
 *
 * This stage exists because CPHD -- the format that makes the sub-aperture
 * strategy possible in the first place -- contains no image. It is pulse-by-
 * pulse phase history, and nothing downstream can run until it is focused.
 *
 * It is also not merely a format workaround. Biondi & Malanga (2022) section
 * 3.1 states that the master and slave sub-bands are "generated by focusing the
 * SAR image, where the matched filter is set to exploit a range-azimuth
 * bandwidth equal to (B_cr, B_cD - B_DL)". Focusing with a restricted, steerable
 * matched-filter band IS the sub-aperture operation. Working from phase history
 * lets the sub-aperture stage do what the method describes; working from an
 * already-focused image only approximates it by filtering after the fact. */

#ifndef RESONARSAT_FOCUS_H
#define RESONARSAT_FOCUS_H

#include <complex.h>
#include <stddef.h>

#include "resonarsat/geocode.h"
#include "resonarsat/resonarsat.h"
#include "resonarsat/slc.h"

/* Range-compressed phase history: one complex signal per transmitted pulse,
 * with the platform position recorded at each pulse.
 *
 * 'signal' is row-major [pulse][range_bin] and holds 'n_pulse * n_rbin'
 * samples. Range bins are uniformly spaced in slant range starting at 'r_near'
 * with spacing 'dr'. The data are assumed already range-compressed; raw
 * unmatched pulses must be compressed by the reader before arriving here, since
 * the chirp parameters are a format concern rather than a focusing one. */
typedef struct rs_cphd {
    float complex *signal;   /* [pulse][range_bin], owned */
    size_t n_pulse, n_rbin;

    double *pos;             /* 3 * n_pulse platform positions, m, owned */
    double *t;               /* n_pulse pulse times, s, owned */

    /* Per-pulse slant range to the scene reference point, metres.
     *
     * Spotlight phase history is motion-compensated: the receive window follows
     * the scene, so range bin n_rbin/2 of every pulse corresponds to the
     * reference point rather than to a fixed absolute range. Without this the
     * collected swath would have to span the whole variation of range over the
     * dwell -- for a 20 s collect at 7.5 km/s that is several kilometres, so a
     * metre-scale swath would contain the target for only the first instant of
     * the aperture and be empty thereafter. */
    double *r_ref;           /* n_pulse reference ranges, m, owned */

    /* Whether the recorded phase is referenced to 'r_ref' or to absolute range.
     *
     * Zero means each sample carries exp(-j*4*pi*R/lambda) for the absolute
     * two-way range R, which is what a simulator naturally produces. Non-zero
     * means the phase is referenced to the scene point, exp(-j*4*pi*(R-r_ref)/
     * lambda), which is what a real collect contains: the receiver demodulates
     * against the tracked reference as it goes, so the reference delay is
     * already removed from the data.
     *
     * Getting this wrong does not degrade an image, it destroys it. Undoing an
     * absolute-range phase on reference-relative data leaves a residual
     * exp(+j*4*pi*r_ref/lambda), and r_ref moves by tens of kilometres over a
     * long dwell -- thousands of cycles of pulse-to-pulse phase error, so
     * nothing sums coherently and the result is indistinguishable from noise.
     * The failure is silent, which is why the flag is explicit rather than
     * inferred. */
    int phase_ref_srp;

    double r_near;           /* fallback absolute range of bin 0 when r_ref is flat, m */
    double dr;               /* slant-range bin spacing, m */
    double fc;               /* carrier frequency, Hz */
    double lambda;           /* wavelength, m */
    double prf;              /* pulse repetition frequency, Hz */

    /* The scene plane the platform positions were expressed in, carried so a
     * focused grid cell can be located on the earth. */
    rs_geo_plane_t plane;

    char source[64];
} rs_cphd_t;

/* Ground grid onto which phase history is focused.
 *
 * A regular rectangular grid in a local east-north-up frame whose origin is
 * 'origin'. 'n_x' by 'n_y' cells of size 'dx' by 'dy' metres, with x along the
 * azimuth (platform track) direction and y across it. Every grid cell sits at
 * height 'height' above the origin plane; a DEM-following grid is a later
 * refinement and would change only this struct and the position lookup. */
typedef struct rs_grid {
    double origin[3];
    size_t n_x, n_y;
    double dx, dy;
    double height;
} rs_grid_t;

/* Allocate a phase-history container for 'n_pulse' pulses of 'n_rbin' range
 * bins. Zeroes the signal, position and time arrays. Returns RS_ERR_ALLOC on
 * failure with nothing allocated, and RS_ERR_ARG for zero dimensions. */
resonarsat_status_t rs_cphd_alloc(rs_cphd_t *cphd, size_t n_pulse, size_t n_rbin);

/* Release every buffer a phase-history container owns and zero its dimensions.
 * Safe on a partially constructed container. */
void rs_cphd_free(rs_cphd_t *cphd);

/* Focus a contiguous window of pulses into an image, by time-domain
 * backprojection.
 *
 * 'pulse_start' and 'pulse_count' select the window; passing 0 and
 * cphd->n_pulse focuses the full aperture. The window is the whole point of
 * this interface: the sub-aperture stage forms its looks by calling this
 * function N times over shifted windows, which is the faithful implementation
 * of the paper's section 3.1 rather than an approximation of it.
 *
 * For every grid cell and every pulse in the window, the two-way slant range is
 * computed exactly from the recorded platform position, the range-compressed
 * pulse is interpolated at that delay, and the sample is accumulated with the
 * phase term exp(+j*4*pi*R/lambda) that removes the carrier. Backprojection is
 * chosen over frequency-domain algorithms because it makes no far-field or
 * planar-wavefront approximation -- which matters over the multi-second dwells
 * this method needs -- and because it accepts an arbitrary pulse subset without
 * any change of formulation.
 *
 * Range interpolation is linear between bins by default; rs_focus_opts_t's
 * range_taps selects a windowed sinc, and carries the measurement and the
 * reference implementations that motivated it.
 *
 * CHECKED AGAINST A PEER. The PERFECT Suite's SAR backprojection kernel (PNNL
 * and Georgia Tech, suite/sar/kernels/ser/bp/src/sar_backprojection.c) is the
 * same algorithm in the same language, and the comparison came out favourably
 * on the two things easiest to get wrong and hardest to notice:
 *
 *   PHASE CONVENTION. It applies exp(+j*2*ku*R) with ku = 2*pi*fc/c, which is
 *   exp(+j*4*pi*R/lambda). This file's k_phase is 4*pi/lambda and the sign is
 *   the same. A wrong sign defocuses and a wrong factor of two halves the
 *   resolution, so agreeing here is worth stating.
 *
 *   ACCUMULATOR PRECISION, where this implementation is the better of the two.
 *   PERFECT accumulates into a float complex and interpolates with a float
 *   weight; this accumulates into two doubles. Over the 335,141 pulses of the
 *   Giza collect -- 327 times their largest configuration -- that is not a
 *   cosmetic difference.
 *
 * Their per-pixel loop, exact range from platform position, fractional bin
 * index, bounds test and private accumulation all match this one.
 *
 * Cost is O(n_grid_cells * pulse_count) and dominates the pipeline's profile.
 * A 2048-squared grid over 20000 pulses is of order 1e11 interpolations, so
 * this runs in minutes on a patch and is the reason crop tooling exists. The
 * loop over grid cells is parallelised with OpenMP when available.
 *
 * 'img' must be an allocated image of grid->n_y by grid->n_x samples; the
 * function fills its samples and the geometry fields it can derive, leaving
 * orbit and Doppler metadata to the caller. Returns RS_ERR_ARG if the image
 * dimensions do not match the grid. */
resonarsat_status_t rs_focus_backproject(const rs_cphd_t *cphd,
                                         const rs_grid_t *grid,
                                         size_t pulse_start,
                                         size_t pulse_count,
                                         rs_slc_t *img);

/* Options that change how backprojection runs, never what it computes.
 *
 * 'single_thread' suppresses the OpenMP parallel region, running the grid on one
 * thread in ascending cell order. Set by --no-optimize.
 *
 * READ THIS BEFORE CITING THE FLAG AS A NUMERICAL CONTROL. It does not change
 * the result, at all, in any bit. The parallel loop is over grid CELLS and each
 * cell accumulates into its own two local doubles over pulses in strictly
 * ascending order; no accumulator is shared between threads, no reduction clause
 * is used, and no partial sums are combined. So the sum for a given cell is the
 * same sequence of additions in the same order regardless of how many threads
 * run, and the output is bitwise identical for any thread count. tests/
 * test_focus.c asserts exactly that, which is the honest way to support the
 * claim -- an untested claim of determinism is worth nothing, and this project
 * has been burned by plausible-looking output before.
 *
 * That makes the flag a reproducibility CHECK rather than a fix: it exists so
 * the above can be verified on a given machine and compiler, and so a run can be
 * profiled or debugged serially. If a future change introduces a shared
 * accumulator, this flag becomes load-bearing and the test will catch the
 * difference. What it is not is a remedy for rounding drift -- there is none
 * here to remedy. */
typedef struct {
    int single_thread;

    /* Number of taps for the range interpolator. 0 or 2 keeps the linear
     * interpolation described above; 4, 8 or 16 select a Hann-windowed sinc.
     *
     * WHY THIS IS AN OPTION AND NOT A FIX. Linear interpolation is convolution
     * with a triangle kernel, whose response is sinc^2(f/fs). If the
     * range-compressed signal fills the sampled band -- which CPHD FX-domain
     * sampling gives, since the bin spacing is set by the transmitted bandwidth
     * -- the band edge is attenuated by sinc^2(0.5), which is -7.9 dB, and the
     * residual folds back as aliasing. That error is not random across pulses:
     * the fractional bin position varies smoothly with slant range along the
     * aperture, so it is coherent, and coherent range error shows up as
     * structure in cross-range.
     *
     * TWO INDEPENDENT REFERENCE IMPLEMENTATIONS UPSAMPLE BY EXACTLY EIGHT
     * BEFORE INTERPOLATING, which is worth more than either one alone:
     *
     *   NGA's MATLAB_SAR (Processing/IFP/BP/bpBasic.m) sets its FFT length to
     *   2^(3+nextpow2(N)) with the comment that the linear interpolation which
     *   follows "causes cross-range artifacts unless we sinc interpolate first
     *   with a much larger FFT size than necessary. Thus the '3+'."
     *
     *   The PERFECT Suite (PNNL and Georgia Tech, DARPA PERFECT programme;
     *   suite/sar/kernels/ser/bp) defines RANGE_UPSAMPLE_FACTOR 8, indexes the
     *   upsampled grid, and its driver prints the native and upsampled bin
     *   resolutions side by side. Its inner loop is otherwise this one.
     *
     * So the correction is standard practice rather than one group's taste, and
     * the 2-tap default here is a deliberate deviation from it. Zero-padding is
     * what neither of them had to think twice about and what this pipeline
     * cannot do: eight times an eleven-gigabyte load is not a trade available
     * here, so the same correction goes into the kernel instead, costing
     * arithmetic in the hot loop rather than memory.
     *
     * MEASURED before deciding, on the Giza collect, and the numbers are in
     * tests/test_focus.c: about 1.4 dB of amplitude, uniformly, with image
     * contrast unchanged to four significant figures and sub-look coherence
     * unchanged. So it is a gain rather than the artefact cleanup the warnings
     * describe, and it changes no conclusion this project draws -- which report
     * frequencies, with amplitudes already labelled qualitative.
     *
     * It stays off by default for that reason and one more: every result in
     * runs/ was produced with the 2-tap path, and flipping the default would
     * make new runs bitwise incomparable with the recorded ones. With the
     * coefficient table the cost is now about 10-25% rather than the 3-4x it
     * was, so that reasoning is worth revisiting deliberately rather than by
     * drift. */
    int range_taps;
} rs_focus_opts_t;

/* As rs_focus_backproject(), with execution options.
 *
 * 'opts' may be NULL, which selects the defaults (threaded). See
 * rs_focus_opts_t for what the options do -- and, for 'single_thread', what it
 * pointedly does not do. */
resonarsat_status_t rs_focus_backproject_opts(const rs_cphd_t *cphd,
                                              const rs_grid_t *grid,
                                              size_t pulse_start,
                                              size_t pulse_count,
                                              const rs_focus_opts_t *opts,
                                              rs_slc_t *img);

/* Convenience wrapper: allocate 'img' to the grid dimensions and focus the full
 * aperture into it. The caller still owns 'img' and must rs_slc_free() it. */
resonarsat_status_t rs_focus_full(const rs_cphd_t *cphd,
                                  const rs_grid_t *grid,
                                  rs_slc_t *img);

/* Return the azimuth resolution in metres that focusing 'pulse_count' pulses of
 * 'cphd' can achieve, given the platform speed implied by the recorded
 * positions.
 *
 * Compare this against the grid cell size before trusting a focused image.
 * Backprojecting onto a grid coarser than the achievable resolution ALIASES:
 * the point spread function is narrower than one cell, and each true scatterer
 * acquires a train of ghost peaks several cells away that look exactly like
 * additional scatterers. On a synthetic scene with one target this is obvious;
 * on a real structure it is not, and it is precisely the class of artefact that
 * must never be mistaken for discovered structure.
 *
 * Either choose a cell at or below this value, or accept a deliberately
 * multi-looked image and say so. Returns 0.0 if the geometry cannot be
 * determined from the container. */
double rs_focus_azimuth_resolution(const rs_cphd_t *cphd, size_t pulse_count);

/* Write a phase-history container to a file, and read one back.
 *
 * The format is a small binary header followed by the position, time and signal
 * arrays, little-endian, intended purely as an interchange between the
 * simulator and the focusing stage. It is not a standard and is not a substitute
 * for a real CPHD reader; a magic number and version guard it so that a stale
 * or foreign file fails with RS_ERR_FORMAT rather than being misread. */
resonarsat_status_t rs_cphd_write(const rs_cphd_t *cphd, const char *path);
resonarsat_status_t rs_cphd_read(rs_cphd_t *cphd, const char *path);

#endif /* RESONARSAT_FOCUS_H */
